# Generated by Django 5.1.7 on 2025-12-15 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('users', '0003_alter_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this user manages (if they are a manager).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='branches.branch'),
        ),
    ]
