# Generated by Django 5.1.7 on 2025-12-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging Token for Push Notifications', max_length=255, null=True),
        ),
    ]
