# Generated by Django 5.1.7 on 2025-12-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('latitude', models.FloatField(help_text='Decimal Coordinate (e.g. 33.6844)')),
                ('longitude', models.FloatField(help_text='Decimal Coordinate (e.g. 73.0479)')),
                ('timing', models.CharField(default='9:00 AM - 11:00 PM', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='branches/')),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
    ]
