# Generated by Django 5.1.7 on 2025-12-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Contact number for the person uploading the prescription', max_length=20, null=True),
        ),
    ]
