# Generated by Django 5.1.7 on 2025-12-14 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_prescription_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Contact number (e.g. 03128424013)', max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 11 digits and start with 03 (e.g., 03128424013) with no spaces or characters.', regex='^03\\d{9}$')]),
        ),
    ]
