# Generated by Django 5.1.7 on 2025-12-15 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('prescriptions', '0004_alter_prescription_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='branches.branch'),
        ),
    ]
