# Generated by Django 5.1.7 on 2026-01-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0005_prescription_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='notes',
        ),
        migrations.AddField(
            model_name='prescription',
            name='address',
            field=models.TextField(default='No Address'),
            preserve_default=False,
        ),
    ]
