# Generated by Django 5.1.7 on 2026-01-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_remove_prescription_notes_prescription_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='note',
            field=models.TextField(blank=True, help_text='Optional note from the user.', null=True),
        ),
    ]
