# Generated by Django 5.1.7 on 2025-12-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Quick', 'Quick')], default='Normal', max_length=10),
        ),
    ]
