# Generated by Django 5.1.7 on 2025-12-14 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_deliverycharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be 11 digits and start with 03 (e.g., 03XXXXXXXXX) with no spaces or characters.', regex='^03\\d{9}$')]),
        ),
    ]
