# Generated by Django 5.1.7 on 2026-01-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_type',
            field=models.CharField(choices=[('Pack', 'Pack'), ('Strip', 'Strip'), ('Unit', 'Unit')], default='Unit', max_length=10),
        ),
    ]
