# Generated by Django 5.1.7 on 2026-01-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderitem_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_manual_price',
            field=models.BooleanField(default=False, help_text='If checked, the backend will respect the provided price. If unchecked, it will auto-calculate based on Unit Type.'),
        ),
    ]
