# Generated by Django 5.1.7 on 2026-01-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_generic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price per Pack'),
        ),
        migrations.AddField(
            model_name='product',
            name='strip_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price per Strip'),
        ),
        migrations.AddField(
            model_name='product',
            name='strips_in_pack',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Strips in Pack'),
        ),
        migrations.AddField(
            model_name='product',
            name='tablets_in_strip',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tablets in Strip'),
        ),
    ]
